import {supabase} from './api';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {League,Rankings,Season,Report,Match,Payload,Stat,PlayerRank} from './league-types';
import {phases} from './league-types';
import './portal.css';
let db=supabase as SupabaseClient|null;
const demo=import.meta.env.DEV && new URLSearchParams(location.search).get('demo')==='1';
const root=document.querySelector<HTMLDivElement>('#app')!;
const params=new URLSearchParams(location.search);
const isAdminPage=location.pathname==='/admin';
const page=location.pathname.split('/')[1]||'inicio';
let league:League; let rankings:Rankings={teams:[],players:[]}; let seasonId=params.get('season')||'';
const phase=params.get('phase')||'regular'; const adminView=params.get('view')||'inicio';
let view:HTMLElement; let flashMessage='';
const n=<K extends keyof HTMLElementTagNameMap>(tag:K,cls='',text?:string)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;};
function link(text:string,href:string,cls=''){const a=n('a',cls,text);a.href=demo&&href.startsWith('/')?href+(href.includes('?')?'&':'?')+'demo=1':href;return a;}
function btn(text:string,fn:()=>void,cls='secondary'){const b=n('button',cls,text);b.type='button';b.onclick=fn;return b;}
function badge(text:string,cls=''){return n('span',`pill ${cls}`,text);}
function club(id:string){return league.clubs.find(c=>c.id===id)?.name||'Club no disponible';}
function player(id:string){return league.players.find(c=>c.id===id)?.name||'Jugador no disponible';}
function season(){return league.seasons.find(s=>s.id===seasonId);}
function currentClub(slot:string){return league.stints.filter(s=>s.slot_id===slot).sort((a,b)=>b.start_round-a.start_round)[0]?.club_id||'';}
function activeClubs(){return league.clubs.filter(c=>league.stints.some(st=>st.club_id===c.id&&league.slots.some(sl=>sl.id===st.slot_id&&sl.season_id===seasonId)));}
function blank(title:string,description:string,action?:HTMLElement){const e=n('section','empty-state');e.append(n('div','empty-orbit','C'),n('h2','',title),n('p','muted',description));if(action)e.append(action);return e;}
function heading(title:string,description:string,action?:HTMLElement){const h=n('div','section-heading');const t=n('div');t.append(n('div','eyebrow','LIGA CNA / CLUBS PRO'),n('h1','',title),n('p','muted',description));h.append(t);if(action)h.append(action);return h;}
function number(v:unknown){return v===null||v===undefined?'—':String(v);}
function table(headers:string[],rows:(string|HTMLElement)[][]){const wrap=n('div','table-scroll');const t=n('table','league-table');const head=n('thead');const tr=n('tr');headers.forEach(h=>tr.append(n('th','',h)));head.append(tr);const body=n('tbody');rows.forEach(cells=>{const row=n('tr');cells.forEach((cell,i)=>{const td=n('td',i===1?'name-cell':'');typeof cell==='string'?td.textContent=cell:td.append(cell);row.append(td);});body.append(row);});t.append(head,body);wrap.append(t);return wrap;}
function card(title:string,subtitle:string,action?:HTMLElement){const c=n('section','portal-card');c.append(n('h2','',title),n('p','muted',subtitle));if(action)c.append(action);return c;}
const errors:Record<string,string>={SUBMISSION_HAS_REPORT:'Esta captura ya tiene un reporte. Revisa el borrador existente.',ADMIN_REQUIRED:'Tu cuenta no tiene permiso de administrador.',MODE_HAS_DATA:'Esta temporada ya tiene datos. Conserva su modo de carga para evitar duplicados.',CLUB_ALREADY_ENROLLED:'El club ya participa en esta temporada.',REPLACEMENT_CONFLICT:'La jornada de reemplazo se cruza con partidos ya cargados o con el inicio del club anterior.',CLUB_NOT_ACTIVE:'Uno de los clubes no ocupa ese cupo en la jornada indicada.',CLUB_NOT_ENROLLED:'Primero inscribe el club en la temporada.',PLAYER_ALREADY_REGISTERED:'El jugador ya tiene una plantilla. Usa la opción de traspaso.',TRANSFER_CONFLICT:'El traspaso se cruza con otra inscripción o con estadísticas ya aprobadas.',PLAYER_NOT_REGISTERED:'Un jugador no está en la plantilla de ese club para esa jornada.',STATS_EXCEED_SCORE:'Los goles o asistencias de los jugadores superan el marcador de su club.',MATCH_MODE_REQUIRED:'Esta temporada usa resúmenes históricos, no partidos.',SUMMARY_MODE_REQUIRED:'Esta temporada se calcula por partidos.',REPORT_NOT_DRAFT:'Guarda una corrección como borrador antes de aprobarla.',SCORE_REQUIRED:'Falta el marcador.',MATCH_CONFLICT:'El partido ya está asociado a otro reporte.'};
function errorText(e:unknown){const m=e&&typeof e==='object'&&'message' in e?String(e.message):String(e);for(const [key,value] of Object.entries(errors))if(m.includes(key))return value;if(m.includes('duplicate key'))return 'Ya existe ese registro. Revisa el nombre, ID de EA o partido antes de repetirlo.';if(m.includes('check constraint')||m.includes('invalid input'))return 'Revisa los campos: hay un valor fuera del rango permitido.';if(m.includes('IA')||m.includes('captura'))return m;return 'No se pudo guardar. Revisa la conexión y los datos e inténtalo otra vez.';}
async function mutate(action:string,data:object){const {data:id,error}=await db!.rpc('cna_manage',{p_action:action,p_data:data});if(error)throw error;return id as string;}
async function fetchData(){const {data,error}=await db!.rpc('cna_league_data');if(error)throw error;league=data as League;if(!seasonId||!league.seasons.some(s=>s.id===seasonId))seasonId=league.seasons[0]?.id||'';const all=page==='historial'||page==='club'||page==='jugador';const r=await db!.rpc('cna_rankings',{p_season:all?null:seasonId||null,p_phase:phase});if(r.error)throw r.error;rankings=r.data as Rankings;}
async function refresh(message=''){flashMessage=message;await fetchData();render();}
function changeQuery(key:string,value:string){const q=new URLSearchParams(location.search);q.set(key,value);location.href=location.pathname+'?'+q.toString();}
function brand(){const a=link('','/','portal-brand');a.append(n('span','brand-mark','C'));const t=n('span');t.append(n('strong','','LIGA CNA'),n('small','','CLUBS PRO · COMPETENCIA & HISTORIA'));a.append(t);return a;}
function render(){root.replaceChildren();document.title='Liga CNA · '+(isAdminPage?'Administración':'La liga, en un solo lugar');const header=n('header','portal-header');header.append(brand());const nav=n('nav','portal-nav');nav.setAttribute('aria-label','Navegación principal');for(const [label,path] of [['Inicio','/'],['Temporadas','/temporadas'],['Tabla','/tabla'],['Partidos','/partidos'],['Jugadores','/jugadores'],['Historial','/historial']]){const a=link(label,path);if(location.pathname===path)a.setAttribute('aria-current','page');nav.append(a);}header.append(nav,link(league.admin?'Mi panel':'Administrar','/admin','nav-admin'));root.append(header);view=n('main','portal-main');root.append(view);
 if(demo)view.append(n('div','notice','DEMOSTRACIÓN LOCAL · Datos ficticios. Ningún cambio se envía a Liga CNA.'));
 if(flashMessage){const f=n('div','success-banner',flashMessage);f.setAttribute('role','status');view.append(f);}
 if(isAdminPage){if(!league.admin){login();return;}renderAdmin();}else renderPublic();
 const footer=n('footer','portal-footer');footer.append(brand(),n('p','','Cada temporada cuenta. Cada resultado tiene historia.'),link('Panel de administración','/admin'));root.append(footer);
}
function filters(all=false){const bar=n('div','season-bar');if(!all){const label=n('label','','Temporada');const select=n('select');select.setAttribute('aria-label','Temporada');if(!league.seasons.length){const o=n('option','','Sin temporadas publicadas');o.value='';select.append(o);}league.seasons.forEach(s=>{const o=n('option','',s.name+(s.published?'':' · borrador'));o.value=s.id;select.append(o);});select.value=seasonId;select.onchange=()=>changeQuery('season',select.value);label.append(select);bar.append(label);}const label=n('label','','Fase');const p=n('select');p.setAttribute('aria-label','Fase');for(const [value,text] of [['regular','Liga regular'],['playoffs','Eliminatorias'],['all','Todas las fases']]){const o=n('option','',text);o.value=value;p.append(o);}p.value=phase;p.onchange=()=>changeQuery('phase',p.value);label.append(p);bar.append(label);if(season()?.data_mode==='summary'&&!all)bar.append(badge('Histórico cargado por totales'));return bar;}
function standings(all=false){if(!rankings.teams.length)return blank('La tabla empieza aquí','Las posiciones aparecerán al publicar una temporada con clubes inscritos.');const rows=rankings.teams.map((r,i)=>{const id=all?r.id:currentClub(r.id);const name=n('div','club-label');name.append(link(club(id),'/club/'+id));if(!all){const chain=league.stints.filter(s=>s.slot_id===r.id);if(chain.length>1)name.append(n('small','',`Cupo heredado · ${chain.map(s=>club(s.club_id)).join(' → ')}`));}return [String(i+1),name,number(r.pj),number(r.wins),number(r.draws),number(r.losses),number(r.gf),number(r.ga),number(r.gd),n('strong','points',number(r.points))];});const wrap=n('section','portal-card table-card');wrap.append(table(['#','Club / cupo','PJ','V','E','D','GF','GC','DG','Pts'],rows),n('p','table-note',all?'Cada club conserva solo los puntos que ganó. No se duplican puntos heredados.':'El cupo conserva los puntos de sus clubes anteriores. Desempates: puntos, diferencia de goles y goles a favor. Una igualdad total sigue pendiente de desempate deportivo.'));return wrap;}
function playerTable(){const metric=params.get('metric')||'goals';const keys:Record<string,string>={goals:'Goleadores',assists:'Asistidores',rating:'Calificación',clean_sheets:'Vallas invictas',saves:'Atajadas'};const wrap=n('section','portal-card table-card');const tabs=n('div','metric-tabs');for(const [k,v] of Object.entries(keys))tabs.append(btn(v,()=>changeQuery('metric',k),metric===k?'tab-selected':'tab-button'));wrap.append(tabs);const sorted=[...rankings.players].sort((a,b)=>{const av=a[metric as keyof PlayerRank] as number|null;const bv=b[metric as keyof PlayerRank] as number|null;return (bv??-1)-(av??-1)||player(a.id).localeCompare(player(b.id));});if(!sorted.length){wrap.append(blank('Todavía no hay estadísticas','Las estadísticas aparecerán después de aprobar reportes o cargar el historial.'));return wrap;}wrap.append(table(['#','Jugador','PJ','Goles','Asist.','Media','VI','Ataj.','GC'],sorted.map((p,i)=>[String(i+1),link(player(p.id),'/jugador/'+p.id),number(p.appearances),number(p.goals),number(p.assists),number(p.rating),number(p.clean_sheets),number(p.saves),number(p.conceded)])),n('p','table-note','— significa dato no disponible. Los totales suman los datos registrados; no implican cobertura completa. La media se pondera por partidos con calificación.'));return wrap;}
function matchList(items:Match[],editable=false){const list=n('div','match-list');if(!items.length){list.append(blank('Sin partidos cargados',season()?.data_mode==='summary'?'Esta temporada conserva tablas finales. No se inventan partidos para reconstruirlas.':'Aquí aparecerán el calendario y los resultados aprobados.'));return list;}items.forEach(m=>{const row=n('article','match-card');const meta=n('div','match-meta');meta.append(badge(m.status==='approved'?'Finalizado':'Programado',m.status==='approved'?'green':''),n('span','',`${phases.find(p=>p[0]===m.phase)?.[1]||m.phase} · J${m.round}`),n('time','',m.played_at||'Fecha por definir'));const score=n('div','scoreline');score.append(link(club(m.home_club),'/club/'+m.home_club),n('strong','',m.status==='approved'?`${m.home_goals} : ${m.away_goals}`:'VS'),link(club(m.away_club),'/club/'+m.away_club));row.append(meta,score);const detail=n('details','match-detail');detail.append(n('summary','','Ver estadísticas y fuente'));const ps=league.stats.filter(s=>s.match_id===m.id);detail.append(ps.length?table(['Jugador','Club','G','A','Media','Ataj.'],ps.map(s=>[link(player(s.player_id),'/jugador/'+s.player_id),club(s.club_id),number(s.goals),number(s.assists),number(s.rating),number(s.saves)])):n('p','muted','No se cargaron estadísticas individuales.'));if(m.source)detail.append(n('p','source-note','Fuente: '+m.source));row.append(detail);if(editable)row.append(btn(m.status==='scheduled'?'Cargar resultado':'Corregir reporte',()=>reportForm(league.reports.find(r=>r.id===m.report_id),m)));list.append(row);});return list;}
function filteredMatches(){return league.matches.filter(m=>m.season_id===seasonId&&(phase==='all'||(phase==='regular'?m.phase==='regular':m.phase!=='regular')));}
function renderPublic(){if(page==='inicio'){const hero=n('section','league-hero');const text=n('div','hero-copy');text.append(badge('EA FC · CLUBS PRO','hero-badge'),n('h1','','LA LIGA.\nSU HISTORIA.'),n('p','','Resultados, protagonistas y temporadas que dejan huella. Todo Liga CNA, en un solo lugar.'));const actions=n('div','hero-actions');actions.append(link('Ver la tabla ↗','/tabla','primary'),link('Explorar el historial','/historial','hero-link'));text.append(actions);const art=n('div','pitch-art');art.setAttribute('aria-hidden','true');art.append(n('div','pitch-line'),n('div','pitch-circle'),n('strong','','CNA'),n('span','','JUEGA. COMPITE. DEJA HUELLA.'));hero.append(text,art);view.append(hero);const strip=n('div','number-strip');for(const [value,label] of [[league.seasons.length,'Temporadas'],[league.clubs.length,'Clubes'],[league.players.length,'Jugadores'],[league.matches.filter(m=>m.status==='approved').length,'Partidos registrados']]){const c=n('div');c.append(n('strong','',String(value)),n('span','',String(label)));strip.append(c);}view.append(strip,heading('La temporada, al día','Consulta la competición actual y sus protagonistas.'),filters());if(!league.seasons.length){view.append(blank('Una nueva etapa para Liga CNA','Estamos incorporando las temporadas y su historial. Aquí aparecerán los datos oficiales, sin resultados de ejemplo.',league.admin?link('Crear primera temporada','/admin?view=temporadas','primary'):undefined));return;}const grid=n('div','home-grid');const left=n('section');left.append(n('h2','block-title','Posiciones'),standings());const right=n('section');right.append(n('h2','block-title','Últimos partidos'),matchList(filteredMatches().slice(0,3)));grid.append(left,right);view.append(grid);}
 else if(page==='temporadas'){view.append(heading('Cada temporada, una historia','Explora la competición actual y el archivo de Liga CNA.'));const grid=n('div','season-grid');league.seasons.forEach(s=>{const c=card(s.name,String(s.year),link('Explorar temporada ↗','/tabla?season='+s.id,'card-link'));c.prepend(badge(s.status==='active'?'En curso':'Archivo',s.status==='active'?'green':''));c.append(n('p','small-muted',s.data_mode==='summary'?'Archivo por totales':'Resultados partido a partido'));grid.append(c);});view.append(grid);if(!league.seasons.length)view.append(blank('El archivo está por comenzar','Las temporadas publicadas aparecerán aquí.'));}
 else if(page==='tabla'){view.append(heading('Tabla de posiciones','La clasificación oficial de la temporada.'),filters(),standings());renderReplacements();}
 else if(page==='partidos'){view.append(heading('Calendario y resultados','Cada partido conserva a los clubes que realmente lo jugaron.'),filters(),matchList(filteredMatches()));}
 else if(page==='jugadores'){view.append(heading('Los protagonistas','Goleadores, asistidores y rendimiento de arqueros.'),filters(),playerTable());}
 else if(page==='historial'){view.append(heading('El legado de Liga CNA','Todas las temporadas. Una historia que sigue creciendo.'),filters(true));const tabs=n('div','metric-tabs');const players=params.get('ranking')==='players';tabs.append(link('Puntos históricos','/historial?phase='+phase,players?'tab-button':'tab-selected'),link('Jugadores históricos','/historial?ranking=players&phase='+phase,players?'tab-selected':'tab-button'));view.append(tabs,players?playerTable():standings(true));}
 else if(page==='club'||page==='jugador')profile();else{view.append(blank('No encontramos esta página','Vuelve al inicio para seguir explorando.',link('Ir al inicio','/','primary')));}}
function renderReplacements(){const st=league.stints.filter(s=>league.slots.some(sl=>sl.id===s.slot_id&&sl.season_id===seasonId));const replaced=st.filter(s=>s.start_round>1);if(!replaced.length)return;const c=card('Reemplazos de la temporada','El cupo hereda puntos; la identidad y los resultados de cada club se conservan.');replaced.forEach(s=>{const prior=st.find(x=>x.slot_id===s.slot_id&&x.end_round===s.start_round-1);c.append(n('p','timeline-item',`${prior?club(prior.club_id):'Cupo'} → ${club(s.club_id)} · desde J${s.start_round}${s.reason?' · '+s.reason:''}`));});view.append(c);}
function profile(){const id=location.pathname.split('/')[2];const isPlayer=page==='jugador';const entity=isPlayer?league.players.find(p=>p.id===id):league.clubs.find(c=>c.id===id);if(!entity){view.append(blank('Perfil no disponible','Puede pertenecer a una temporada que todavía no está publicada.'));return;}view.append(heading(entity.name,isPlayer?'Trayectoria y estadísticas registradas':'Identidad propia. Resultados propios.'),link('← Volver al historial','/historial','card-link'));if(isPlayer){const p=league.players.find(p=>p.id===id)!;view.append(badge(p.position+' · '+p.ea_id));const own=rankings.players.find(p=>p.id===id);if(own)view.append(table(['PJ','Goles','Asistencias','Media','VI','Atajadas'],[[number(own.appearances),number(own.goals),number(own.assists),number(own.rating),number(own.clean_sheets),number(own.saves)]]));const c=card('Trayectoria','Plantillas y traspasos por temporada');league.rosters.filter(r=>r.player_id===id).forEach(r=>c.append(n('p','timeline-item',`${league.seasons.find(s=>s.id===r.season_id)?.name} · ${club(r.club_id)} · J${r.start_round}–${r.end_round??'actualidad'}`)));view.append(c);}else{const own=rankings.teams.find(t=>t.id===id);if(own)view.append(table(['PJ','V','E','D','GF','GC','Puntos propios'],[[number(own.pj),number(own.wins),number(own.draws),number(own.losses),number(own.gf),number(own.ga),number(own.points)]]));const c=card('Participaciones','Los puntos heredados pertenecen a la tabla del cupo y no se suman a este historial.');league.stints.filter(st=>st.club_id===id).forEach(st=>{const sl=league.slots.find(s=>s.id===st.slot_id);c.append(n('p','timeline-item',`${league.seasons.find(s=>s.id===sl?.season_id)?.name} · J${st.start_round}–${st.end_round??'fin de temporada'}`));});view.append(c);const roster=card('Jugadores','Plantillas registradas por temporada');league.rosters.filter(r=>r.club_id===id).forEach(r=>{const p=n('p','timeline-item');p.append(link(player(r.player_id),'/jugador/'+r.player_id),n('span','',` · ${league.seasons.find(s=>s.id===r.season_id)?.name} · J${r.start_round}–${r.end_round??'fin'}`));roster.append(p);});view.append(roster,matchList(league.matches.filter(m=>m.home_club===id||m.away_club===id)));}}
type Field={key:string;label:string;type?:string;options?:string[][];value?:unknown;required?:boolean;min?:number;max?:number;help?:string};
function field(f:Field){const wrap=n('label','form-field',f.label);const input=f.options?n('select'):f.type==='textarea'?n('textarea'):n('input');input.name=f.key;if(input instanceof HTMLInputElement){input.type=f.type||'text';if(f.min!==undefined)input.min=String(f.min);if(f.max!==undefined)input.max=String(f.max);if(f.type==='number')input.step=f.key.startsWith('rating')?'0.1':'1';}if(input instanceof HTMLSelectElement){const placeholder=n('option','','Selecciona…');placeholder.value='';input.append(placeholder);}if(input instanceof HTMLSelectElement)f.options!.forEach(([value,label])=>{const o=n('option','',label);o.value=value;input.append(o);});if(f.value!=null)input.value=String(f.value);input.required=f.required!==false;wrap.append(input);if(f.help)wrap.append(n('small','',f.help));return wrap;}
function modal(title:string,description:string){const dialog=n('dialog','edit-dialog');const head=n('div','dialog-head');head.append(n('h2','',title),btn('Cerrar ×',()=>dialog.close(),'text-button'));dialog.append(head,n('p','muted',description));const form=n('form','admin-form');dialog.append(form);root.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();return {dialog,form};}
function formAction(form:HTMLFormElement,dialog:HTMLDialogElement,label:string,run:(fd:FormData)=>Promise<unknown>){const actions=n('div','form-actions');const error=n('p','error');error.setAttribute('role','alert');const submit=n('button','primary',label);submit.type='submit';actions.append(btn('Cancelar',()=>dialog.close()),submit);form.append(error,actions);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;error.textContent='';try{await run(new FormData(form));dialog.close();await refresh('Guardado correctamente.');}catch(e){error.textContent=errorText(e);}finally{submit.disabled=false;}};}
function values(fd:FormData){const out:Record<string,unknown>={};fd.forEach((v,k)=>{out[k]=v===''?null:v;});return out;}
function simpleForm(title:string,description:string,fields:Field[],action:string,extra:object={},label='Guardar'){const {dialog,form}=modal(title,description);fields.forEach(f=>form.append(field(f)));formAction(form,dialog,label,fd=>mutate(action,{...values(fd),...extra}));}
function login(){view.append(heading('Tu liga. Bajo control.','Inicia sesión con tu cuenta de administrador.'));const c=n('section','login-panel');const f=n('form','admin-form');f.append(field({key:'email',label:'Correo electrónico',type:'email'}),field({key:'password',label:'Contraseña',type:'password'}));const error=n('p','error');error.setAttribute('role','alert');const b=n('button','primary','Entrar al panel');b.type='submit';f.append(error,b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;error.textContent='';const fd=new FormData(f);try{const r=await db!.auth.signInWithPassword({email:String(fd.get('email')).trim(),password:String(fd.get('password'))});if(r.error)throw r.error;await fetchData();if(!league.admin)throw new Error('ADMIN_REQUIRED');render();}catch(e){const err=e as {code?:string};error.textContent=err.code==='invalid_credentials'?'Correo o contraseña incorrectos.':String(e).includes('ADMIN_REQUIRED')?'Tu cuenta no tiene permiso de administrador.':'El servicio de acceso no responde. Vuelve a intentarlo en unos minutos.';}finally{b.disabled=false;}};c.append(f);view.append(c);}
function renderAdmin(){view.append(heading('Centro de la liga','Organiza el presente. Conserva la historia.',btn('Cerrar sesión',async()=>{await db!.auth.signOut();location.href='/';})));const nav=n('nav','admin-tabs');for(const [k,label] of [['inicio','Guía de armado'],['temporadas','Temporadas'],['clubes','Clubes'],['jugadores','Jugadores'],['plantillas','Cupos y plantillas'],['partidos','Partidos y revisión'],['archivo','Carga histórica']])nav.append(link(label,`/admin?view=${k}&season=${seasonId}`,adminView===k?'tab-selected':'tab-button'));nav.append(link('Capturas ↗','/admin/submissions','tab-button'));view.append(nav);if(adminView==='inicio'){const grid=n('div','guide-grid');for(const [num,title,desc,target] of [['01','Crea la temporada','Elige partidos completos o resúmenes históricos. Empieza como borrador.','temporadas'],['02','Registra a los protagonistas','Crea clubes y jugadores una vez; conserva su identidad en el tiempo.','clubes'],['03','Arma los cupos y plantillas','Inscribe clubes, jugadores y reemplazos desde una jornada concreta.','plantillas'],['04','Carga y revisa los resultados','Guarda borradores y aprueba cuando los datos estén correctos.','partidos'],['05','Completa el archivo','Carga tablas antiguas sin inventar estadísticas que no tienes.','archivo'],['06','Publica la temporada','Revisa la información y hazla visible para toda la liga.','temporadas']]){const c=card(title,desc,link('Abrir →',`/admin?view=${target}&season=${seasonId}`,'card-link'));c.prepend(n('div','step-number',num));grid.append(c);}view.append(grid,card('Capturas y lectura con IA','Las capturas y los borradores son privados. La IA propone los datos; solo tu aprobación modifica la web.',link('Abrir bandeja de capturas','/admin/submissions','card-link')));return;}
 if(adminView==='temporadas'){view.append(btn('+ Nueva temporada',()=>seasonForm(), 'primary'));const grid=n('div','season-grid');league.seasons.forEach(s=>{const c=card(s.name,`${s.year} · ${s.data_mode==='matches'?'Por partidos':'Resúmenes históricos'}`);c.prepend(badge(s.published?'Publicada':'Borrador',s.published?'green':''));const a=n('div','card-actions');a.append(link('Gestionar',`/admin?view=plantillas&season=${s.id}`,'secondary'),btn('Editar',()=>seasonForm(s)),btn(s.published?'Retirar de la web':'Publicar',()=>confirmAction(s.published?'Retirar temporada':'Publicar temporada',s.published?'La temporada dejará de ser pública. Sus datos se conservan.':'Los resultados aprobados, clubes y jugadores de esta temporada serán públicos.',()=>mutate('publish',{season_id:s.id,published:!s.published}))));c.append(a);grid.append(c);});view.append(grid);return;}
 if(adminView==='clubes'){view.append(btn('+ Registrar club',()=>clubForm(),'primary'));view.append(table(['Club','Abrev.','Acción'],league.clubs.map(c=>[c.name,c.abbreviation,btn('Editar',()=>clubForm(c))])));return;}
 if(adminView==='jugadores'){view.append(btn('+ Registrar jugador',()=>playerForm(),'primary'));view.append(table(['Jugador','ID de EA / consola','Posición','Acción'],league.players.map(p=>[p.name,p.ea_id,p.position,btn('Editar',()=>playerForm(p))])));return;}
 view.append(filters());if(!season()){view.append(blank('Primero crea una temporada','Luego podrás inscribir clubes y cargar resultados.',btn('Crear temporada',()=>seasonForm(),'primary')));return;}
 if(adminView==='plantillas')adminRosters();if(adminView==='partidos')adminMatches();if(adminView==='archivo')adminArchive();}
function confirmAction(title:string,description:string,action:()=>Promise<unknown>){const {dialog,form}=modal(title,description);formAction(form,dialog,title,action);}
function seasonForm(s?:Season){simpleForm(s?'Editar temporada':'Nueva temporada','Una temporada nueva se guarda como borrador. Publica cuando hayas revisado sus datos.',[{key:'name',label:'Nombre',value:s?.name},{key:'year',label:'Año',type:'number',min:1990,max:2100,value:s?.year||new Date().getFullYear()},{key:'data_mode',label:'Modo de carga',options:[['matches','Tengo resultados partido por partido'],['summary','Solo tengo tablas y totales históricos']],value:s?.data_mode||'matches',help:'No se mezclan los dos modos para evitar contar datos dos veces.'},{key:'win_points',label:'Puntos por victoria',type:'number',min:0,max:10,value:s?.win_points??3},{key:'draw_points',label:'Puntos por empate',type:'number',min:0,max:10,value:s?.draw_points??1},{key:'status',label:'Estado',options:[['active','En curso'],['archived','Finalizada / histórica']],value:s?.status||'active'}],'season',s?{id:s.id}:{});}
function clubForm(c?:{id:string;name:string;abbreviation:string}){simpleForm(c?'Editar identidad del club':'Registrar club','Para reemplazar un club usa «Reemplazar» en Cupos y plantillas. No renombres al club anterior.',[{key:'name',label:'Nombre del club',value:c?.name},{key:'abbreviation',label:'Abreviatura (hasta 6 caracteres)',value:c?.abbreviation}],'club',c?{id:c.id}:{});}
function playerForm(p?:{id:string;name:string;ea_id:string;position:string}){simpleForm(p?'Editar jugador':'Registrar jugador','La identidad del jugador se conserva al cambiar de club o temporada.',[{key:'name',label:'Nombre público',value:p?.name},{key:'ea_id',label:'ID de EA / PSN / Xbox',value:p?.ea_id},{key:'position',label:'Posición',options:[['POR','Arquero'],['DEF','Defensor'],['MED','Mediocampista'],['DEL','Delantero']],value:p?.position||'MED'}],'player',p?{id:p.id}:{});}
function adminRosters(){const actions=n('div','card-actions');actions.append(btn('+ Inscribir club',()=>simpleForm('Inscribir club','Cada cupo conserva sus puntos aunque cambie el club.',[{key:'club_id',label:'Club',options:league.clubs.map(c=>[c.id,c.name])},{key:'label',label:'Nombre del cupo',value:`Cupo ${league.slots.filter(s=>s.season_id===seasonId).length+1}`},{key:'start_round',label:'Desde jornada',type:'number',min:1,max:999,value:1}],'enroll',{season_id:seasonId}),'primary'),btn('+ Inscribir / traspasar jugador',()=>simpleForm('Asignar jugador a una plantilla','Un traspaso cierra la inscripción anterior desde la jornada elegida; los partidos previos conservan el club real.',[{key:'player_id',label:'Jugador',options:league.players.map(p=>[p.id,p.name+' · '+p.ea_id])},{key:'club_id',label:'Club',options:activeClubs().map(c=>[c.id,c.name])},{key:'start_round',label:'Desde jornada',type:'number',min:1,max:999,value:1},{key:'transfer',label:'Si ya está inscrito',options:[['false','No modificar la plantilla anterior'],['true','Registrar traspaso y cerrar la anterior']],value:'false'}],'roster',{season_id:seasonId})));view.append(actions);const grid=n('div','season-grid');league.slots.filter(s=>s.season_id===seasonId).forEach(sl=>{const st=league.stints.filter(st=>st.slot_id===sl.id);const c=card(club(currentClub(sl.id)),sl.label);st.forEach(s=>c.append(n('p','timeline-item',`${club(s.club_id)} · J${s.start_round}–${s.end_round??'fin'}`)));c.append(btn('Reemplazar club',()=>simpleForm('Reemplazo con herencia','El nuevo club hereda los puntos del cupo. Las victorias, derrotas y estadísticas anteriores siguen perteneciendo al club original.',[{key:'club_id',label:'Nuevo club',options:league.clubs.map(c=>[c.id,c.name])},{key:'start_round',label:'Primera jornada del reemplazante',type:'number',min:2,max:999,value:2},{key:'reason',label:'Motivo (visible en el historial)',required:false}],'replace',{slot_id:sl.id})));grid.append(c);});view.append(grid);view.append(n('h2','block-title','Plantillas y traspasos'),table(['Jugador','Club','Desde','Hasta'],league.rosters.filter(r=>r.season_id===seasonId).map(r=>[player(r.player_id),club(r.club_id),'J'+r.start_round,r.end_round?'J'+r.end_round:'Fin de temporada'])));}
function adminMatches(){if(params.get('submission')){view.append(card('Captura seleccionada','Puedes transcribirla manualmente o pedir una lectura con Claude. La IA necesita su API configurada y nunca aprueba resultados.',btn('Leer captura con IA',()=>extractForm())));}if(season()?.data_mode==='summary'){view.append(blank('Esta temporada usa resúmenes','Carga sus tablas finales desde Carga histórica.',link('Cargar historial',`/admin?view=archivo&season=${seasonId}`,'primary')));return;}const actions=n('div','card-actions');actions.append(btn('+ Cargar resultado',()=>reportForm(),'primary'),btn('+ Programar partido',()=>scheduleForm()));view.append(actions,n('h2','block-title','Reportes para revisar'));const reports=league.reports.filter(r=>r.season_id===seasonId);if(!reports.length)view.append(n('p','muted','No hay reportes. Carga un resultado manual o abre una captura recibida.'));reports.forEach(r=>{const c=card(`${club(r.payload.home_club)} ${number(r.payload.home_goals)} : ${number(r.payload.away_goals)} ${club(r.payload.away_club)}`,`J${r.payload.round} · ${r.status==='approved'?'Aprobado':r.status==='rejected'?'Rechazado':'Pendiente de revisión'}`);c.append(btn('Revisar reporte',()=>review(r)));view.append(c);});view.append(n('h2','block-title','Calendario y resultados oficiales'),matchList(filteredMatches(),true));}
function matchFields(body?:Partial<Payload>):Field[]{return [{key:'phase',label:'Fase',options:phases,value:body?.phase||'regular'},{key:'round',label:'Jornada / fecha de competición',type:'number',min:1,max:999,value:body?.round||1},{key:'home_club',label:'Club local',options:activeClubs().map(c=>[c.id,c.name]),value:body?.home_club},{key:'away_club',label:'Club visitante',options:activeClubs().map(c=>[c.id,c.name]),value:body?.away_club},{key:'played_at',label:'Fecha del partido',type:'date',required:false,value:body?.played_at}];}
function scheduleForm(){simpleForm('Programar partido','El calendario no suma puntos ni estadísticas hasta aprobar su resultado.',matchFields(),'schedule',{season_id:seasonId});}
function reportForm(rep?:Report,m?:Match){const body:Partial<Payload>|undefined=rep?.payload||(m?{...m,players:league.stats.filter(s=>s.match_id===m.id),match_id:m.id}:undefined);const {dialog,form}=modal(rep?'Corregir reporte':'Cargar resultado','Guarda un borrador, revisa y aprueba. Deja en blanco las estadísticas que no conoces.');matchFields(body).forEach(f=>form.append(field(f)));form.append(field({key:'home_goals',label:'Goles local',type:'number',min:0,max:99,value:body?.home_goals}),field({key:'away_goals',label:'Goles visitante',type:'number',min:0,max:99,value:body?.away_goals}),field({key:'source',label:'Fuente / enlace de Copa Fácil o Instagram',required:false,value:body?.source}));const rows=n('div','stat-editor');form.append(n('h3','full-width','Estadísticas individuales (opcional)'),rows);let count=0;function addStat(s?:Stat){const i=count++;const row=n('fieldset','stat-row');row.dataset.index=String(i);row.append(n('legend','','Jugador '+(i+1)));const fs:Field[]=[{key:`p${i}`,label:'Jugador',options:league.players.filter(p=>league.rosters.some(r=>r.season_id===seasonId&&r.player_id===p.id)).map(p=>[p.id,p.name]),value:s?.player_id},{key:`c${i}`,label:'Club en este partido',options:activeClubs().map(c=>[c.id,c.name]),value:s?.club_id},...(['goals','assists','rating','saves','conceded'] as const).map((key,j)=>({key:key+i,label:['Goles','Asistencias','Calificación','Atajadas','Goles recibidos'][j],type:'number',min:0,max:key==='rating'?10:999,required:false,value:s?.[key]})),{key:'cs'+i,label:'Valla invicta (arquero)',options:[['','No disponible'],['true','Sí'],['false','No']],required:false,value:s?.clean_sheet==null?'':String(s.clean_sheet)}];fs.forEach(f=>row.append(field(f)));row.append(btn('Quitar jugador',()=>row.remove(),'text-button'));rows.append(row);}body?.players?.forEach(addStat);form.append(btn('+ Agregar jugador',()=>addStat()));formAction(form,dialog,'Guardar borrador',async fd=>{const v=values(fd);const stats:Stat[]=[];rows.querySelectorAll<HTMLElement>('.stat-row').forEach(row=>{const i=row.dataset.index!;const num=(k:string)=>v[k+i]==null?null:Number(v[k+i]);stats.push({player_id:String(v['p'+i]),club_id:String(v['c'+i]),goals:num('goals'),assists:num('assists'),rating:num('rating'),saves:num('saves'),conceded:num('conceded'),clean_sheet:v['cs'+i]==null?null:v['cs'+i]==='true'});});const payload={phase:v.phase,round:Number(v.round),home_club:v.home_club,away_club:v.away_club,home_goals:Number(v.home_goals),away_goals:Number(v.away_goals),played_at:v.played_at,source:v.source||'',players:stats,...(body?.match_id?{match_id:body.match_id}:{})};return mutate('report',{id:rep?.id,season_id:seasonId,submission_id:rep?.submission_id||params.get('submission'),payload});});}
function review(rep:Report){const {dialog,form}=modal('Revisar reporte',`${club(rep.payload.home_club)} ${rep.payload.home_goals} : ${rep.payload.away_goals} ${club(rep.payload.away_club)} · J${rep.payload.round}`);const p=rep.payload;form.append(table(['Jugador','Club','G','A','Media'],(p.players||[]).map(s=>[player(s.player_id),club(s.club_id),number(s.goals),number(s.assists),number(s.rating)])));if(rep.submission_id)form.append(link('Consultar captura original ↗','/admin/submissions/'+rep.submission_id,'card-link'));if(rep.ai_output){form.append(n('p','notice','Este reporte contiene extracción de IA. Verifica nombres, marcador y datos. Los nombres sin coincidencia deben asignarse manualmente.'));const details=n('details','full-width');details.append(n('summary','','Ver lectura original de IA'),n('pre','ai-output',JSON.stringify(rep.ai_output,null,2)));form.append(details);}form.append(n('p','muted','Al aprobar, este resultado actualizará la tabla y las estadísticas. Si la temporada está publicada, el cambio será público.'),btn('Editar datos',()=>{dialog.close();reportForm(rep);}),btn('Rechazar',()=>{dialog.close();simpleForm('Rechazar reporte','No se publicarán sus datos.',[{key:'note',label:'Motivo',type:'textarea'}],'reject',{id:rep.id},'Rechazar');}));if(rep.status==='draft')formAction(form,dialog,'Aprobar y actualizar la liga',()=>mutate('approve',{id:rep.id}));else form.append(n('p','notice',rep.status==='approved'?'Reporte aprobado. Para corregirlo, edita y vuelve a aprobar.':'Reporte rechazado. Puedes editarlo para volver a revisar.'));}
function adminArchive(){if(season()?.data_mode!=='summary'){view.append(blank('Carga partido por partido','Esta temporada calcula sus tablas a partir de partidos aprobados. Para un archivo con solo totales, crea una temporada de resúmenes.',link('Cargar partidos',`/admin?view=partidos&season=${seasonId}`,'primary')));return;}view.append(card('Carga histórica sin inventar datos','Ingresa únicamente los totales propios de cada club. Si hubo reemplazo, no vuelvas a cargar los puntos heredados en el nuevo club. Los resúmenes se consideran de liga regular; los campos individuales desconocidos quedan en blanco.'));const actions=n('div','card-actions');actions.append(btn('+ Totales de club',()=>clubSummary(),'primary'),btn('+ Totales de jugador',()=>playerSummary()));view.append(actions,table(['Club','V','E','D','GF','GC','Fuente',''],league.club_summaries.filter(x=>x.season_id===seasonId).map(x=>[club(x.club_id),number(x.wins),number(x.draws),number(x.losses),number(x.gf),number(x.ga),x.source,btn('Editar',()=>clubSummary(x))])),table(['Jugador','Club','PJ','G','A','Fuente',''],league.player_summaries.filter(x=>x.season_id===seasonId).map(x=>[player(x.player_id),club(x.club_id),number(x.appearances),number(x.goals),number(x.assists),x.source,btn('Editar',()=>playerSummary(x))])));}
function clubSummary(x?:League['club_summaries'][number]){simpleForm('Totales históricos del club','Guarda los resultados que jugó este club. Esta carga actualizará directamente las tablas de una temporada publicada.',[{key:'club_id',label:'Club',options:activeClubs().map(c=>[c.id,c.name]),value:x?.club_id},...(['wins','draws','losses','gf','ga'] as const).map((k,i)=>({key:k,label:['Victorias','Empates','Derrotas','Goles a favor','Goles en contra'][i],type:'number',min:0,max:9999,value:x?.[k]})),{key:'source',label:'Fuente / enlace del archivo',value:x?.source}],'club_summary',{season_id:seasonId},'Confirmar y guardar totales');}
function playerSummary(x?:League['player_summaries'][number]){simpleForm('Totales históricos del jugador','Si no conoces un dato, déjalo vacío. Usa totales de este jugador en este club y temporada.',[{key:'player_id',label:'Jugador',options:league.players.map(p=>[p.id,p.name]),value:x?.player_id},{key:'club_id',label:'Club',options:activeClubs().map(c=>[c.id,c.name]),value:x?.club_id},...(['appearances','goals','assists','rating','clean_sheets','saves','conceded'] as const).map((k,i)=>({key:k,label:['Partidos','Goles','Asistencias','Media de calificación','Vallas invictas','Atajadas','Goles recibidos'][i],type:'number',min:0,max:k==='rating'?10:9999,required:false,value:x?.[k]})),{key:'source',label:'Fuente / enlace del archivo',value:x?.source}],'player_summary',{season_id:seasonId},'Confirmar y guardar totales');}
function extractForm(){if(import.meta.env.VITE_AI_ENABLED!=='true'){const {form}=modal('Lectura automática pendiente','La lectura con IA aún no está activada. Puedes cargar el reporte manualmente y vincular esta captura.');form.append(n('p','notice','Falta conectar y validar el proveedor de IA. Ninguna captura se enviará desde este botón.'));return;}const {dialog,form}=modal('Leer captura con Claude','Se enviará esta captura a Anthropic para extraer un borrador. Ningún resultado oficial cambiará.');form.append(field({key:'round',label:'Jornada del partido',type:'number',min:1,max:999,value:1}));formAction(form,dialog,'Analizar captura',async fd=>{const {data,error}=await db!.functions.invoke('cna-extract',{body:{submission_id:params.get('submission'),season_id:seasonId,round:Number(fd.get('round'))}});if(error){let message='No se pudo leer la captura. Revisa la configuración de IA.';try{const details=await error.context.json();message=details.message||message;}catch{}throw new Error(message);}if(data.error)throw new Error(data.message||data.error);});} async function start(){root.replaceChildren(n('div','page-loading','Cargando Liga CNA…'));try{if(demo)db=await (await import('./dev-fixture')).fixture() as unknown as SupabaseClient;if(!db)throw new Error('Missing configuration');await fetchData();render();}catch{root.replaceChildren(blank('No pudimos cargar la liga','El servidor puede estar iniciándose. Reintenta en unos momentos.',btn('Reintentar',()=>void start(),'primary')));}}
void start();




